[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"

# Handle SPA routing - this redirects any unknown paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 